version: '3.8'

services:
  app:
    image: controle-oficios # Se você já tem a imagem construída, use isso. Se não, construa abaixo.
    build: 
      context: .
      dockerfile: ProgramaOficios.API/Dockerfile  # Caminho para o Dockerfile da aplicação
    ports:
      - "8080:80"  # Mapear porta 8080 do host para 80 do contêiner
    environment:
      - SQL_CONNECTION_STRING: "${SQL_CONNECTION_STRING}"

      - AZURE_BLOB_STORAGE: "${AZURE_BLOB_STORAGE}"

    depends_on:
      - db # Define que a aplicação depende do serviço de banco de dados

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: dbbbo599c6ngkl
      POSTGRES_USER: ud0arjusr9bfqq
      POSTGRES_PASSWORD: p1842deed28f58c1c27af3314cdda470f4450f154b31e971fc21c2e7ba914b3c9
    ports:
      - "5432:5432"
